services:
  ceramicraft-merchant-frontend:
    build: fe-mer
    hostname: femer.local
    container_name: ceramicraft-merchant-frontend
    networks:
      - ceramicraft
    restart: unless-stopped

  ceramicraft-customer-frontend:
    build: fe-cus
    hostname: fecus.local
    container_name: ceramicraft-customer-frontend
    networks:
      - ceramicraft
    restart: unless-stopped

  ceramicraft-user-mservice:
    build: ms-user/server
    hostname: msuser.local
    container_name: ceramicraft-user-mservice
    environment:
      MYSQL_PASSWORD=${DB_PASSWORD}
      SMTP_PASSWORD=${SMTP_PASSWORD}
      SMTP_EMAIL_FROM=${SMTP_USERNAME}
      JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ceramicraft
    restart: unless-stopped

  ceramicraft-cmdt-mservice:
    build: ms-cmdt/server
    hostname: mscmdt.local
    container_name: ceramicraft-cmdt-mservice
    environment:
      MYSQL_PASSWORD=${DB_PASSWORD}
      SMTP_PASSWORD=${SMTP_PASSWORD}
      SMTP_EMAIL_FROM=${SMTP_USERNAME}
      JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ceramicraft
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    hostname: ${DB_HOSTNAME}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ceramicraft
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "ceramicraft", "-pceramicraft123"]
      timeout: 10s
      retries: 10
      interval: 5s
      start_period: 20s

  nginx:
    image: nginx:1.28
    hostname: nginx.local
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - ceramicraft-merchant-frontend
      - ceramicraft-customer-frontend
      - ceramicraft-user-mservice
    networks:
      - ceramicraft
    restart: unless-stopped

networks:
  ceramicraft:
    driver: "bridge"

volumes:
  mysql_data:
    driver: local
