{
 "title": "Commodity Service Monitoring",
 "tags": [
  "order-service",
  "go",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "label": "Endpoint",
    "query": "label_values(order_service_http_requests_total, path)"
   }
  ]
 },
 "panels": [
  {
   "title": "QPS per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(path) (rate(http_requests_total{job=\"product-service\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Error Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(path) (increase(http_errors_total{job=\"product-service\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "P95 Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(path, le) (rate(http_request_duration_milliseconds_bucket{job=\"product-service\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 response time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_milliseconds_bucket{job=\"product-service\"}[5m]))by(path, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"product-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"product-service\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage （%）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"product-service\"}[1m]) * 50",
     "legendFormat": "CPU Seconds"
    }
   ]
  }
 ]
}