{
 "title": "Order Service Monitoring",
 "tags": [
  "order-service",
  "go",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "label": "Endpoint",
    "query": "label_values(order_service_http_requests_total, path)"
   }
  ]
 },
 "panels": [
  {
   "title": "QPS per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(order_service_http_requests_total[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Error Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(order_service_errors_total[5m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "P99 Response time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(order_service_http_request_duration_milliseconds_bucket[5m])) by (path, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(order_service_http_request_duration_milliseconds_bucket[5m])) by (path, le))",
     "legendFormat": "{{path}} P95"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"order-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"order-service\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage （%）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"order-service\"}[1m]) * 50",
     "legendFormat": "CPU Seconds"
    }
   ]
  }
 ]
}